services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

  backend:
    container_name: backend
    build:
      context: ../Backend/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - HOST=${HOST}
      - PORT=${PORT}

  database:
    container_name: postgre-db
    image: postgres:16.3-bookworm
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}