export const DASHBOARD = "/dashboard",
  PRICING_PlANS = `${DASHBOARD}/pricing-plan`,
  SUBSCRIPTIONS = `${DASHBOARD}/subscriptions`,
  FEES = `${DASHBOARD}/fee`,
  OVERRATE_FEE = `${DASHBOARD}/overrate-fee`,
  FEATURES = `${DASHBOARD}/features`,
  PERMISSIONS = `${DASHBOARD}/permissions`,
  USERS = `${DASHBOARD}/users`,
  LANDING_PAGE = `${DASHBOARD}/landing-page`;
