import { PricingPlan } from "@/interfaces/model/pricingplan.type";

export const DummyData: PricingPlan[] = [
  {
    id: "plan-id-1",
    name: "Pricing Plan 1",
    start_date: "",
    end_date: "",
    price: 0,
    description: null,
    has_free_trial: false,
    free_trial_period: null,
    free_trial_period_count: null,
    recurrence_fee_id: null,
    is_active: false,
    features: [
      {
        feature: {
          id: "feature-id-1",
          name: "Feature 1",
          description: null,
          permissions: [],
          is_active: false,
          created_at: "2024-07-30T00:00:00.000Z",
          updated_at: "2024-07-30T00:00:00.000Z",
        },
        new_price: null,
        fee: null,
        feature_plan_fee_new_overrate: null,
      },
    ],
  },
  {
    id: "plan-id-2",
    name: "Pricing Plan 2",
    start_date: "",
    end_date: "",
    price: 0,
    description: null,
    has_free_trial: false,
    free_trial_period: null,
    free_trial_period_count: null,
    recurrence_fee_id: null,
    is_active: false,
    features: [
      {
        feature: {
          id: "feature-id-2",
          name: "Feature 2",
          description: null,
          permissions: [],
          is_active: false,
          created_at: "2024-07-30T00:00:00.000Z",
          updated_at: "2024-07-30T00:00:00.000Z",
        },
        new_price: null,
        fee: null,
        feature_plan_fee_new_overrate: null,
      },
    ],
  },
  {
    id: "plan-id-3",
    name: "Pricing Plan 3",
    start_date: "",
    end_date: "",
    price: 0,
    description: null,
    has_free_trial: false,
    free_trial_period: null,
    free_trial_period_count: null,
    recurrence_fee_id: null,
    is_active: false,
    features: [
      {
        feature: {
          id: "feature-id-3",
          name: "Feature 3",
          description: null,
          permissions: [],
          is_active: false,
          created_at: "2024-07-30T00:00:00.000Z",
          updated_at: "2024-07-30T00:00:00.000Z",
        },
        new_price: null,
        fee: null,
        feature_plan_fee_new_overrate: null,
      },
    ],
  },
  {
    id: "plan-id-4",
    name: "Pricing Plan 4",
    start_date: "",
    end_date: "",
    price: 0,
    description: null,
    has_free_trial: false,
    free_trial_period: null,
    free_trial_period_count: null,
    recurrence_fee_id: null,
    is_active: false,
    features: [
      {
        feature: {
          id: "feature-id-4",
          name: "Feature 4",
          description: null,
          permissions: [],
          is_active: false,
          created_at: "2024-07-30T00:00:00.000Z",
          updated_at: "2024-07-30T00:00:00.000Z",
        },
        new_price: null,
        fee: null,
        feature_plan_fee_new_overrate: null,
      },
    ],
  },
  {
    id: "plan-id-5",
    name: "Pricing Plan 5",
    start_date: "",
    end_date: "",
    price: 0,
    description: null,
    has_free_trial: false,
    free_trial_period: null,
    free_trial_period_count: null,
    recurrence_fee_id: null,
    is_active: false,
    features: [
      {
        feature: {
          id: "feature-id-5",
          name: "Feature 5",
          description: null,
          permissions: [],
          is_active: false,
          created_at: "2024-07-30T00:00:00.000Z",
          updated_at: "2024-07-30T00:00:00.000Z",
        },
        new_price: null,
        fee: null,
        feature_plan_fee_new_overrate: null,
      },
    ],
  },
  {
    id: "plan-id-6",
    name: "Pricing Plan 6",
    start_date: "",
    end_date: "",
    price: 0,
    description: null,
    has_free_trial: false,
    free_trial_period: null,
    free_trial_period_count: null,
    recurrence_fee_id: null,
    is_active: false,
    features: [
      {
        feature: {
          id: "feature-id-6",
          name: "Feature 6",
          description: null,
          permissions: [],
          is_active: false,
          created_at: "2024-07-30T00:00:00.000Z",
          updated_at: "2024-07-30T00:00:00.000Z",
        },
        new_price: null,
        fee: null,
        feature_plan_fee_new_overrate: null,
      },
    ],
  },
  {
    id: "plan-id-7",
    name: "Pricing Plan 7",
    start_date: "",
    end_date: "",
    price: 0,
    description: null,
    has_free_trial: false,
    free_trial_period: null,
    free_trial_period_count: null,
    recurrence_fee_id: null,
    is_active: false,
    features: [
      {
        feature: {
          id: "feature-id-7",
          name: "Feature 7",
          description: null,
          permissions: [],
          is_active: false,
          created_at: "2024-07-30T00:00:00.000Z",
          updated_at: "2024-07-30T00:00:00.000Z",
        },
        new_price: null,
        fee: null,
        feature_plan_fee_new_overrate: null,
      },
    ],
  },
];
