import { PricingPlan } from "@/interfaces/model/pricingplan.type";
export const DummyData: PricingPlan[] = [
  {
    id: "1",
    name: "Basic",
    start_date: "",
    end_date: "",
    price: 50,
    description: "Perfect for side or hobby projects",
    features: [
      {
        id: "1",
        name: "Up to 5 users",
        description: null,
        permissions: [],
        is_active: false,
        created_at: "",
        updated_at: "",
      },
      {
        id: "2",
        name: "Collaboration features",
        description: null,
        permissions: [],
        is_active: false,
        created_at: "",
        updated_at: "",
      },
    ],
    is_free_trial: false,
    free_trial_period: null,
    free_trial_period_count: null,
    is_active: false,
  },
  {
    id: "3",
    name: "Premium",
    start_date: "",
    end_date: "",
    price: 200,
    description: "For large teams and enterprises",
    features: [
      {
        id: "5",
        name: "Unlimited users",
        description: null,
        permissions: [],
        is_active: false,
        created_at: "",
        updated_at: "",
      },
      {
        id: "6",
        name: "Customizable features",
        description: null,
        permissions: [],
        is_active: false,
        created_at: "",
        updated_at: "",
      },
    ],
    is_free_trial: false,
    free_trial_period: null,
    free_trial_period_count: null,
    is_active: true,
  },
  {
    id: "5",
    name: "Professional",
    start_date: "",
    end_date: "",
    price: 150,
    description: "For growing businesses",
    features: [
      {
        id: "9",
        name: "Up to 20 users",
        description: null,
        permissions: [],
        is_active: false,
        created_at: "",
        updated_at: "",
      },
      {
        id: "10",
        name: "Advanced reporting",
        description: null,
        permissions: [],
        is_active: false,
        created_at: "",
        updated_at: "",
      },
    ],
    is_free_trial: false,
    free_trial_period: null,
    free_trial_period_count: null,
    is_active: false,
  },
];
