import { PricingPlan } from "@/interfaces/model/pricingplan.type";

export const DummyData: PricingPlan[] = [
  {
    id: "1",
    name: "Basic",
    start_date: "",
    end_date: "",
    price: 50,
    description: "Perfect for side or hobby projects",
    features: [
      {
        id: "1",
        name: "Up to 5 users",
        description: null,
        permissions: [],
        is_active: false,
        created_at: "",
        updated_at: "",
      },
      {
        id: "2",
        name: "Collaboration features",
        description: null,
        permissions: [],
        is_active: false,
        created_at: "",
        updated_at: "",
      },
    ],
    is_free_trial: false,
    free_trial_period: null,
    free_trial_period_count: null,
    is_active: false,
    recurrence_fee_name: "Monthly", // Include this if required by the type
  },
  {
    id: "2",
    name: "Premium",
    start_date: "",
    end_date: "",
    price: 100,
    description: "Perfect for small teams",
    features: [
      {
        id: "3",
        name: "Up to 50 users",
        description: null,
        permissions: [],
        is_active: false,
        created_at: "",
        updated_at: "",
      },
      {
        id: "2",
        name: "Collaboration features",
        description: null,
        permissions: [],
        is_active: false,
        created_at: "",
        updated_at: "",
      },
      {
        id: "4",
        name: "Smart analytics",
        description: null,
        permissions: [],
        is_active: false,
        created_at: "",
        updated_at: "",
      },
      {
        id: "5",
        name: "30-day free trial",
        description: null,
        permissions: [],
        is_active: false,
        created_at: "",
        updated_at: "",
      },
    ],
    is_free_trial: false,
    free_trial_period: null,
    free_trial_period_count: null,
    is_active: false,
    recurrence_fee_name: "Monthly", // Include this if required by the type
  },
  {
    id: "3",
    name: "Pro",
    start_date: "",
    end_date: "",
    price: 150,
    description: "Perfect for side or hobby projects",
    features: [
      {
        id: "6",
        name: "Unlimited users",
        description: null,
        permissions: [],
        is_active: false,
        created_at: "",
        updated_at: "",
      },
      {
        id: "2",
        name: "Collaboration features",
        description: null,
        permissions: [],
        is_active: false,
        created_at: "",
        updated_at: "",
      },
      {
        id: "4",
        name: "Smart analytics",
        description: null,
        permissions: [],
        is_active: false,
        created_at: "",
        updated_at: "",
      },
      {
        id: "5",
        name: "30-day free trial",
        description: null,
        permissions: [],
        is_active: false,
        created_at: "",
        updated_at: "",
      },
    ],
    is_free_trial: false,
    free_trial_period: null,
    free_trial_period_count: null,
    is_active: false,
    recurrence_fee_name: "Monthly",
  },
  {
    id: "4",
    name: "Basic",
    start_date: "",
    end_date: "",
    price: 5,
    description: "Perfect for side or hobby projects",
    features: [
      {
        id: "1",
        name: "Up to 5 users",
        description: null,
        permissions: [],
        is_active: false,
        created_at: "",
        updated_at: "",
      },
      {
        id: "2",
        name: "Collaboration features",
        description: null,
        permissions: [],
        is_active: false,
        created_at: "",
        updated_at: "",
      },
    ],
    is_free_trial: false,
    free_trial_period: null,
    free_trial_period_count: null,
    is_active: false,
    recurrence_fee_name: "Weekly", // Include this if required by the type
  },
  {
    id: "5",
    name: "Premium",
    start_date: "",
    end_date: "",
    price: 10,
    description: "Perfect for small teams",
    features: [
      {
        id: "3",
        name: "Up to 50 users",
        description: null,
        permissions: [],
        is_active: false,
        created_at: "",
        updated_at: "",
      },
      {
        id: "2",
        name: "Collaboration features",
        description: null,
        permissions: [],
        is_active: false,
        created_at: "",
        updated_at: "",
      },
      {
        id: "4",
        name: "Smart analytics",
        description: null,
        permissions: [],
        is_active: false,
        created_at: "",
        updated_at: "",
      },
      {
        id: "5",
        name: "30-day free trial",
        description: null,
        permissions: [],
        is_active: false,
        created_at: "",
        updated_at: "",
      },
    ],
    is_free_trial: false,
    free_trial_period: null,
    free_trial_period_count: null,
    is_active: false,
    recurrence_fee_name: "Weekly", // Include this if required by the type
  },
  {
    id: "6",
    name: "Pro",
    start_date: "",
    end_date: "",
    price: 15,
    description: "Perfect for side or hobby projects",
    features: [
      {
        id: "6",
        name: "Unlimited users",
        description: null,
        permissions: [],
        is_active: false,
        created_at: "",
        updated_at: "",
      },
      {
        id: "2",
        name: "Collaboration features",
        description: null,
        permissions: [],
        is_active: false,
        created_at: "",
        updated_at: "",
      },
      {
        id: "4",
        name: "Smart analytics",
        description: null,
        permissions: [],
        is_active: false,
        created_at: "",
        updated_at: "",
      },
      {
        id: "5",
        name: "30-day free trial",
        description: null,
        permissions: [],
        is_active: false,
        created_at: "",
        updated_at: "",
      },
    ],
    is_free_trial: false,
    free_trial_period: null,
    free_trial_period_count: null,
    is_active: false,
    recurrence_fee_name: "Weekly",
  },

  {
    id: "7",
    name: "Basic",
    start_date: "",
    end_date: "",
    price: 5,
    description: "Perfect for side or hobby projects",
    features: [
      {
        id: "1",
        name: "Up to 5 users",
        description: null,
        permissions: [],
        is_active: false,
        created_at: "",
        updated_at: "",
      },
      {
        id: "2",
        name: "Collaboration features",
        description: null,
        permissions: [],
        is_active: false,
        created_at: "",
        updated_at: "",
      },
    ],
    is_free_trial: false,
    free_trial_period: null,
    free_trial_period_count: null,
    is_active: false,
    recurrence_fee_name: "Daily", // Include this if required by the type
  },
  {
    id: "8",
    name: "Premium",
    start_date: "",
    end_date: "",
    price: 10,
    description: "Perfect for small teams",
    features: [
      {
        id: "3",
        name: "Up to 50 users",
        description: null,
        permissions: [],
        is_active: false,
        created_at: "",
        updated_at: "",
      },
      {
        id: "2",
        name: "Collaboration features",
        description: null,
        permissions: [],
        is_active: false,
        created_at: "",
        updated_at: "",
      },
      {
        id: "4",
        name: "Smart analytics",
        description: null,
        permissions: [],
        is_active: false,
        created_at: "",
        updated_at: "",
      },
      {
        id: "5",
        name: "30-day free trial",
        description: null,
        permissions: [],
        is_active: false,
        created_at: "",
        updated_at: "",
      },
    ],
    is_free_trial: false,
    free_trial_period: null,
    free_trial_period_count: null,
    is_active: false,
    recurrence_fee_name: "Daily", // Include this if required by the type
  },
  {
    id: "9",
    name: "Pro",
    start_date: "",
    end_date: "",
    price: 15,
    description: "Perfect for side or hobby projects",
    features: [
      {
        id: "6",
        name: "Unlimited users",
        description: null,
        permissions: [],
        is_active: false,
        created_at: "",
        updated_at: "",
      },
      {
        id: "2",
        name: "Collaboration features",
        description: null,
        permissions: [],
        is_active: false,
        created_at: "",
        updated_at: "",
      },
      {
        id: "4",
        name: "Smart analytics",
        description: null,
        permissions: [],
        is_active: false,
        created_at: "",
        updated_at: "",
      },
      {
        id: "5",
        name: "30-day free trial",
        description: null,
        permissions: [],
        is_active: false,
        created_at: "",
        updated_at: "",
      },
    ],
    is_free_trial: false,
    free_trial_period: null,
    free_trial_period_count: null,
    is_active: false,
    recurrence_fee_name: "Yearly",
  },
];
