name: CI/CD Pipeline

on:
  push:
    branches: [develop, uat, 'staging/*']
    tags: ['*.*.*']
  pull_request:
    branches: ['**']


jobs:
  lint-and-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: |
          yarn lint:fix
          yarn format:fix


  build:
    runs-on: ubuntu-latest
    needs: lint-and-check  # Ensure lint passes before building
    steps:
      - uses: actions/checkout@v3
      - name: Build the project
        run: |
          yarn build  # Replace with your build command
