name: Production Build

on:
  pull_request:
    branches:
      - "dev"
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: benjlevesque/short-sha@v3.0
        id: short-sha
        with:
          length: 6

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ${{ github.ref == 'refs/heads/dev' && 'Dockerfile.dev' || '.' }}
          push: true
          tags: |
            ${{ github.ref == 'refs/heads/dev' && 'quocc/sub:frontend-test' || 'quocc/sub:frontend-latest' }}
            ${{ github.ref == 'refs/heads/dev' && 'quocc/sub:frontend-test-${{ steps.short-sha.outputs.sha }}' || 'quocc/sub:frontend-${{ steps.short-sha.outputs.sha }}' }}
          build-args: |
            NEXT_PUBLIC_API_BASE_URL=${{ github.ref == 'refs/heads/dev' && secrets.NEXT_PUBLIC_API_BASE_URL_DEV || secrets.NEXT_PUBLIC_API_BASE_URL }}
            NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}
            NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }}
